###

GET http://localhost:9090/api/v1/
Accept: application/json
Cache-Control: no-cache


###
# SIGN IN
###

POST http://localhost:9090/api/v1/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

userId=user1&password=user1%21

###
# USER
###

GET http://localhost:9090/api/v1/users/user1
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:9090/api/v1/users/user0
Accept: application/json
Cache-Control: no-cache

###
# SUBMISSIONS
###

GET http://localhost:9090/api/v1/submissions
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:9090/api/v1/submissions/2
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:9090/api/v1/submissions
Accept: application/json
Cache-Control: no-cache

{
  "submission": {
    "title": "abc",
    "abstract": "abc",
    "type": "abc",
    "submittedTo": "abc",
    "visibility": "PUBLIC"
  }
}

###

PUT http://localhost:9090/api/v1/submissions
Accept: application/json
Cache-Control: no-cache

{
  "submission": {
    "title": "abc",
    "abstract": "abc",
    "type": "abc",
    "submittedTo": "abc",
    "visibility": "PUBLIC"
  }
}

###

###
# CONFERENCE
###

GET http://localhost:9090/api/v1/conference
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:9090/api/v1/conference/0
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:9090/api/v1/conference/3
Accept: application/json
Cache-Control: no-cache

###
# REGISTER
###

GET http://localhost:9090/api/v1/register
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:9090/api/v1/register?userId=user30&password=p4ss!w0rd&email=u30@keynotedex.co&displayName=1😁2👩🏼3
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:9090/api/v1/register?userId=user40&password=p4ss!w0rd&email=u30@keynotedex.co
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:9090/api/v1/register?userId=user50&password=p4ss&email=u30@keynotedex.co
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:9090/api/v1/register?userId=usr&password=p4ss!w0rd&email=u30@keynotedex.co
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:9090/api/v1/register?userId=user70&password=p4ss!w0rd
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:9090/api/v1/register?userId=user70&password=p4ss!w0rd
Accept: application/json
Cache-Control: no-cache

###

