object Versions {
    const val detekt = "1.0.0-RC12"
    const val ehcache = "3.6.1"
    const val fuel = "1.11.0"
    const val gson = "2.8.0"
    const val html = "0.6.9"
    const val jsoup = "1.9.1"
    const val junit = "4.12"
    const val kotlin = "1.3.11"
    const val kotlinFrontendPlugin = "0.0.37"
    const val kotlinJsExt = "1.0.1-pre.61-kotlin-1.3.0"
    const val kotlinWrapper = "16.6.0-pre.61-kotlin-1.3.0"
    const val kotlinxCoroutines = "1.0.1"
    const val ktor = "1.1.1"
    const val logback = "1.2.1"
    const val node = "8.11.2"
    const val serialization = "0.9.1"
    const val squash = "0.2.4"
}

object Libs {
    const val ehcache = "org.ehcache:ehcache:${Versions.ehcache}"
    const val fuel = "com.github.kittinunf.fuel:fuel:${Versions.fuel}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val jsoup = "org.jsoup:jsoup:${Versions.jsoup}"
    const val junit = "junit:junit:${Versions.junit}"
    const val kotlinExtensions = "org.jetbrains:kotlin-extensions:${Versions.kotlinJsExt}"
    const val kotlinReact = "org.jetbrains:kotlin-react:${Versions.kotlinWrapper}"
    const val kotlinReactDom = "org.jetbrains:kotlin-react-dom:${Versions.kotlinWrapper}"
    const val kotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:${Versions.kotlin}"
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val kotlinStdlibCommon = "org.jetbrains.kotlin:kotlin-stdlib-common:${Versions.kotlin}"
    const val kotlinStdlibJs = "org.jetbrains.kotlin:kotlin-stdlib-js:${Versions.kotlin}"
    const val kotlinTest = "org.jetbrains.kotlin:kotlin-test:${Versions.kotlin}"
    const val kotlinTestCommon = "org.jetbrains.kotlin:kotlin-test-common:${Versions.kotlin}"
    const val kotlinTestJs = "org.jetbrains.kotlin:kotlin-test-js:${Versions.kotlin}"
    const val kotlinTestJunit = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlin}"
    const val kotlinxCoroutinesCoreJs = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js:${Versions.kotlinxCoroutines}"
    const val kotlinxHtmlJs = "org.jetbrains.kotlinx:kotlinx-html-js:${Versions.html}"
    const val kotlinxSerializationRuntime = "org.jetbrains.kotlinx:kotlinx-serialization-runtime:${Versions.serialization}"
    const val kotlinxSerializationRuntimeCommon = "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:${Versions.serialization}"
    const val kotlinxSerializationRuntimeJs = "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:${Versions.serialization}"
    const val ktorClientApache = "io.ktor:ktor-client-apache:${Versions.ktor}"
    const val ktorFreemaker = "io.ktor:ktor-freemarker:${Versions.ktor}"
    const val ktorGson = "io.ktor:ktor-gson:${Versions.ktor}"
    const val ktorHtmlBuilder = "io.ktor:ktor-html-builder:${Versions.ktor}"
    const val ktorLocations = "io.ktor:ktor-locations:${Versions.ktor}"
    const val ktorServerNetty = "io.ktor:ktor-server-netty:${Versions.ktor}"
    const val ktorServerTestHost = "io.ktor:ktor-server-test-host:${Versions.ktor}"
    const val logbackClassic = "ch.qos.logback:logback-classic:${Versions.logback}"
    const val squashH2 = "org.jetbrains.squash:squash-h2:${Versions.squash}"
}
